### PR TITLE
Add falcon-40B to list of open LLMs

### PR DESCRIPTION
**Pull request by adekunleoajayi**
In this PR, I have added falcon-40B to the list of LLB and also a short description of the supporting licence

### CODE REVIEW

**Comment by adekunleoajayi** [comment]
Okay, noted.

**Comment by furuknap** [comment]
Falcon has now been released under Apache 2.0 so I second to inclusion on the list now. Thank you Falcon!

**Comment by LudwigStumpp** [comment]
@adekunleoajayi: Now that we can add Falcon to the list, could you please resolve above conflict?

**Comment by LudwigStumpp** [comment]
Awesome! Just merged it! Thanks for your commitment 🥳

**Pull request closed without merging**
