### PR TITLE
add model release date to table

### PR DESCRIPTION
**Pull request by adekunleoajayi**

### CODE REVIEW

**Comment by Muhtasham** [comment]
LGTM! thanks @adekunleoajayi

**Review by moghadas76 — CHANGES_REQUESTED** [review]
Should you cite the repo url

**Comment by Muhtasham** [comment]
@moghadas76 I think it is fine as there are already links associated with this info in other tables

**Comment by Muhtasham** [comment]
I think it is fine as there are already links associated with this info in other tables

**Pull request merged**
